### ISSUE TITLE
Add option to disable line break removal

### ISSUE THREAD

**Issue by Sebruck** [personio/kotlin-auto-formatter#11]
Currently the formatter removes line breaks when the code still fits into the configured `maxLineLength`.

This can be suboptimal especially when writing DSL-Like code with [Typesafe Builders](https://kotlinlang.org/docs/reference/type-safe-builders.html).

For example
```kotlin
html {
        head {
            title {+"The title"}
        }
}
```

should not be reformatted to

```
html { head { title {+"The title"} } }
```

It would be useful to have an option to deactivate the line break removal for a block of code. Maybe an annotation which can be applied to classes and function could make sense.

**Comment by hovinen** [comment]
Just pushed a first cut at it which covers the case you've highlighted. It'll need some more refinement to really cover the full syntax, though.
