### ISSUE TITLE
Can't format in case of newline after "if" opening parenthesis

### ISSUE THREAD

**Issue by karstenba** [personio/kotlin-auto-formatter#13]
Trying to format the below code snippet runs into `Could not process after.kt (line 1): Could not match node sequence [PsiElement(if), PsiWhiteSpace, PsiElement(LPAR), PsiWhiteSpace, Element(CONDITION), PsiWhiteSpace, PsiElement(RPAR), PsiWhiteSpace, Element(THEN)]`.
```
if (
  1 == 2
) {
}
```

**Comment by hovinen** [comment]
Thanks for reporting this. I've pushed a fix and will do a release after collecting a few more changes.
