### ISSUE TITLE
Formatter attempts to format raw strings

### ISSUE THREAD

**Issue by EclipseOnFire** [personio/kotlin-auto-formatter#14]
The formatter seems to format Kotlin raw strings, which modifies the code's behavior.  
Initial code:
```kotlin
throw UnauthorizedException(
    """
    The client $inetAddress is attempting to read on node ${nodeConfiguration.tag}
    at address {${nodeConfiguration.modbusNode.address.start}.
    """.trimIndent()
)
```

Formatted code:
```kotlin
throw UnauthorizedException(
    """
        The client $inetAddress is attempting to read on node ${nodeConfiguration.tag}
                                            at address {${nodeConfiguration.modbusNode.address.start}.
    """.trimIndent()
)
```

**Comment by hovinen** [comment]
Hi,

I'm having trouble reproducing this issue as presented.

In a test I just rain, the formatted output of

```
throw UnauthorizedException(
    """
    The client $inetAddress is attempting to read on node ${nodeConfiguration.tag}
    at address {${nodeConfiguration.modbusNode.address.start}.
    """.trimIndent()
)
```

is

```
throw UnauthorizedException(
    """
        The client $inetAddress is attempting to read on node ${nodeConfiguration.tag}
        at address {${nodeConfiguration.modbusNode.address.start}.
    """.trimIndent()
)
```

without the larger indent of the second line. This is expected: the formatter modifies multi-line string literals with `trimIndent` calls to use the same indentation rules as the rest of the code, while ensuring that the resulting output of `trimIndent` remains the same.

However, the output in your example *would* be expected if the input were something like the following:

```
throw UnauthorizedException(
    """The client $inetAddress is attempting to read on node ${nodeConfiguration.tag}
    at address {${nodeConfiguration.modbusNode.address.start}.
    """.trimIndent()
)
```

That is, without a newline between the opening  quote and the string. Are you certain that the input has a newline after the opening quote?

In the latter case, the formatted output (while visually strange) does  the behaviour of `trimIndent`: the common indent of all lines of the input to `trimIndent` is 0, so the function has no effect, other than to strip blank leading and trailing lines. In that case, one can avoid the odd formatting by removing the call to `trimIndent`, in which case the formatter will leave the string untouched.

**Comment by EclipseOnFire** [comment]
Hi,

I tried several times to format the code. It seems that it clashes with our IDE formatting settings.  
I disabled it and it now works as described.

The IDE was reformatting the string like the following:
```kotlin
throw UnauthorizedException(
    """The client $inetAddress is attempting to read on node ${nodeConfiguration.tag}
    at address {${nodeConfiguration.modbusNode.address.start}.
    """.trimIndent()
)
```

I wouldn't have found this conflict without your comment.
