### ISSUE TITLE
Formatter does not wrap braces onto the next line

### ISSUE THREAD

**Issue by erikgoe** [personio/kotlin-auto-formatter#15]
Hello,
The formatter seems to not always wrap the closing brace of a function to the next line.
Minimal example:
```kotlin
package app
class Test {
    fun foo() {
        bar()}

    fun bar() {
    }
}
```
I expect a newline before the curly brace in the fourth line.

Shouldn't it add one? AFAIK the Kotlin conventions require the closing brace to be horizontally aligned with the function head.

I found this by accident and thought I should report it.

**Comment by hovinen** [comment]
Thanks for reporting this!. I've pushed a fix so that the formatter fixes this kind of error. It will be included in the next release.

**Comment by erikgoe** [comment]
Thank you. I'm glad I could help.
