### ISSUE TITLE
Annotations in data class parameters not kept in separate lines

### ISSUE THREAD

**Issue by dripolles** [personio/kotlin-auto-formatter#17]
Annotations should be placed on a separate line before the annotated element: https://kotlinlang.org/docs/coding-conventions.html#annotations

```Kotlin
@Target(AnnotationTarget.VALUE_PARAMETER)
annotation class SomeAnnotation(val str: String)

data class Foo(
    @SomeAnnotation("something")
    val foo: Int,
    val bar: Int
)
```

When running the formatter on that source, the annotation is left in the same line as `foo`:

```Kotlin
data class Foo(@SomeAnnotation("something") val foo: Int, val bar: Int)
```

**Comment by hovinen** [comment]
Thanks for reporting this. This behaviour indeed contradicts the coding conventions. I've pushed a fix which forces a line break unless it is a simple annotation.
