### ISSUE TITLE
Long function signatures not properly broken down in lines

### ISSUE THREAD

**Issue by dripolles** [personio/kotlin-auto-formatter#18]
Long function signatures need to be [split with one argument per line](https://kotlinlang.org/docs/coding-conventions.html#functions), like this example:

```Kotlin
fun something(
    thisIsOneLongParameter: String,
    thisIsAnotherLongParameter: Map<String, String>
): String {
    val somethingElse = thisIsOneLongParameter.toUpperCase()

    return thisIsAnotherLongParameter[somethingElse]!!
}
```

When running the formatter, only the return type is moved to a different line:
```Kotlin
fun something(thisIsOneLongParameter: String, thisIsAnotherLongParameter: Map<String, String>):
    String {
        val somethingElse = thisIsOneLongParameter.toUpperCase()

        return thisIsAnotherLongParameter[somethingElse]!!
    }
```

In the case of an expression body, the expression is left on the same line that the return type. On a strict interpretation of the coding conventions, [the expression's first line doesn't fit on the same line as the declaration](https://kotlinlang.org/docs/coding-conventions.html#expression-bodies), as the declaration has more than one line.

Thus, a function with a long signature and an expression body should be formatted like this:

```Kotlin
fun something(
    thisIsOneLongParameter: String,
    thisIsAnotherLongParameter: Map<String, String>
): String =
    thisIsAnotherLongParameter[thisIsOneLongParameter]!!
```

The formatter produces this output:

```Kotlin
fun something(thisIsOneLongParameter: String, thisIsAnotherLongParameter: Map<String, String>):
    String = thisIsAnotherLongParameter[thisIsOneLongParameter]!!
```

**Comment by hovinen** [comment]
Thanks for pointing this out. You're right -- a strict reading of the coding conventions indicates that breaking at the parameter list is required in that case. I've pushed a fix for this.
