### ISSUE TITLE
Some function expression bodies are wrongly split into lines

### ISSUE THREAD

**Issue by dripolles** [personio/kotlin-auto-formatter#19]
This example function with an expression body:

```Kotlin
fun something(one: String, two: String, m: Map<Pair<String, String>, String>): String? =
    m[one to two]
```

Ends up being formatted like this:

```Kotlin
fun something(one: String, two: String, m: Map<Pair<String, String>, String>): String? = m[one to
    two]
```
I am not sure if there are other cases that do that kind of split, we found this one by pure chance.

**Comment by hovinen** [comment]
Thanks for the report. I've pushed a fix and will do a release shortly.
