### ISSUE TITLE
Very long method / property access not split

### ISSUE THREAD

**Issue by dripolles** [personio/kotlin-auto-formatter#20]
In very extreme cases, where a `name.accessor` expression is too long, it is not split and it overflows the max column value. See this example code:

```Kotlin
object ThisObjectHasAVeryLongNameAndShouldNotExist {
    fun thisFunctionHasAnotherVeryLongNameAndThisShouldNeverHappen() {
    }
}

fun foo() {
    ThisObjectHasAVeryLongNameAndShouldNotExist
        .thisFunctionHasAnotherVeryLongNameAndThisShouldNeverHappen()
}
```

After formatting, we get this:

```Kotlin
fun foo() {
   ThisObjectHasAVeryLongNameAndShouldNotExist.thisFunctionHasAnotherVeryLongNameAndThisShouldNeverHappen()
}
```

The line with the method call is longer than 100 columns, and could even trigger a linter error if it's used in combination with the formatter.

**Comment by hovinen** [comment]
Thanks for reporting this. I knew of this corner case a while ago but could not find a solution which worked in all cases. I've pushed a fix which at least covers the key cases and should prevent violating the column limit. I'll push a test version with this fix shortly.
