### ISSUE TITLE
used import for java.util.* is removed

### ISSUE THREAD

**Issue by christophsturm** [personio/kotlin-auto-formatter#3]
in this fragment: 
```
import java.util.*


fun prepareH2(): ConnectionFactory {
    val uuid = UUID.randomUUID()
...
}
```

the formatter removes the java.util.* import and so the file no longer compiles

also the idea autoformatter keeps changing `import java.util.UUID` to `import java.util.*` so this keeps me from using the plugin

**Comment by hovinen** [comment]
Thanks for reporting this! I just committed a fix and will make a new release with the fix this evening.
