### ISSUE TITLE
Statement suppressions are inactivated

### ISSUE THREAD

**Issue by siebenfarben** [personio/kotlin-auto-formatter#6]
We experienced the following example
```kotlin
    @Suppress("UNCHECKED_CAST")
    it as EventProcessor<Any>
```
to be reformatted as
```kotlin
    @Suppress("UNCHECKED_CAST") it as EventProcessor<Any>
```

This actually "inactivates" the suppression and spawns yet another unchecked cast warning. The @Suppress annotation should stay positioned in the line before the statement.

**Comment by hovinen** [comment]
Thanks for reporting this.

Just pushed a fix and will do a new release right away.
